[package]
name = "luxt"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.5.2"
arrayvec = { version = "0.7.6", default-features = false }

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
