[package]
name = "luxt"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
paste = "1.0.15"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[features]
log = []
