[package]
name = "luxt"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
lazy_static = { version = "1.0", features = ["spin_no_std"] }
paste = "1.0.15"
hashbrown = "0.15.0"

[features]
log = []
