[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = ".cargo/i686-unknown-none.json"

[target.'cfg(target_os = "none")']
# runner = "qemu-system-i386 -kernel isodir/boot/kernel.bin -m 128M -vga std -device isa-debug-exit,iobase=0xf4,iosize=0x04 -serial stdio"
runner = "./qemu_runner.sh"
